---
kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  environment:
    PDR_USER:
      from_secret: docker-user-pdr
    PDR_PASS:
      from_secret: docker-pass-pdr
  commands:
  - docker build -t pdr.nephatrine.net/nephatrine/drone-ci:cached --target builder .
  - docker build -t pdr.nephatrine.net/nephatrine/drone-ci:latest .
  - docker login -p "$PDR_PASS" -u "$PDR_USER" pdr.nephatrine.net
  - docker push pdr.nephatrine.net/nephatrine/drone-ci:latest
  - docker logout pdr.nephatrine.net
- name: publish
  environment:
    DOCKER_USER:
      from_secret: docker-user
    DOCKER_PASS:
      from_secret: docker-pass
  commands:
  - docker tag pdr.nephatrine.net/nephatrine/drone-ci:latest nephatrine/drone-ci:latest
  - docker tag pdr.nephatrine.net/nephatrine/drone-ci:latest nephatrine/drone-ci:2.16.0
  - docker tag pdr.nephatrine.net/nephatrine/drone-ci:latest nephatrine/drone-ci:2.16
  - docker tag pdr.nephatrine.net/nephatrine/drone-ci:latest nephatrine/drone-ci:2
  - docker login -p "$DOCKER_PASS" -u "$DOCKER_USER"
  - docker push -a nephatrine/drone-ci
  - docker logout
  depends_on:
  - build

---
kind: pipeline
name: notify

steps:
- name: notify-status
  image: appleboy/drone-discord
  failure: ignore
  settings:
    avatar_url: https://nephatrine.net/images/buttons/drone-ci.png
    message: "Build of **[{{repo.name}}:{{commit.branch}}](<https://code.nephatrine.net/nephatrine/{{repo.name}}/src/branch/{{commit.branch}}>)** returned [{{build.status}}](<{{build.link}}>)."
    username: DroneCI
    webhook_id:
      from_secret: wh-infra-id
    webhook_token:
      from_secret: wh-infra-tok

depends_on:
- default

trigger:
  status:
  - success
  - failure

---
kind: signature
hmac: 84060c4f3f1e3ce9ffeaa7fd25df69612a5142378b71f284c8e60bd8708a041e

...
