FROM nephatrine/alpine-s6:3.9
LABEL maintainer="Daniel Wolf <nephatrine@gmail.com>"

RUN echo "====== INSTALL PACKAGES ======" \
 && apk add \
   docker \
   git \
   sqlite \
 && rm -rf /var/cache/apk/*

ARG DRONE_VERSION=v1.2.3
ARG DRONE_CLI_VERSION=v1.1.4
ENV DRONE_EXEC_DISABLED=true

RUN echo "====== COMPILE DRONE ======" \
 && apk add --virtual .build-drone build-base go \
 && cd /usr/src \
 && git clone -b "$DRONE_VERSION" --single-branch https://github.com/drone/drone && cd drone \
 && go install -tags nolimit ./cmd/drone-server \
 && mv /root/go/bin/drone-server /usr/bin/ \
 && go install ./cmd/drone-agent \
 && mv /root/go/bin/drone-agent /usr/bin/ \
 && mkdir -p /root/go/src/github.com/drone && cd /root/go/src/github.com/drone \
 && git clone -b "$DRONE_CLI_VERSION" --single-branch https://github.com/drone/drone-cli && cd drone-cli \
 && go install ./... \
 && mv /root/go/bin/drone /usr/bin/ \
 && cd /usr/src && rm -rf /root/go /usr/src/* \
 && apk del --purge .build-drone && rm -rf /var/cache/apk/*

COPY override /

EXPOSE 8080/tcp