#!/usr/bin/with-contenv bash

/etc/cont-init.d/01-drone
if [[ -e /mnt/config/etc/drone/config ]]; then
  . /mnt/config/etc/drone/config
fi

export DRONE_AGENTS_ENABLED=${DRONE_AGENTS_ENABLED:-"true"}
export DRONE_DATABASE_DRIVER=${DRONE_DATABASE_DRIVER:-"sqlite3"}
export DRONE_DATABASE_DATASOURCE=${DRONE_DATABASE_DATASOURCE:-"/mnt/config/data/drone/db/drone.db"}
export DRONE_RPC_SECRET=${DRONE_RPC_SECRET:-"$(libressl rand -hex 16)"}
export DRONE_SERVER_PROTO=${DRONE_SERVER_PROTO:-"http"}
export DRONE_SERVER_HOST=${DRONE_SERVER_HOST:-"127.0.0.1"}

exec s6-setuidgid guardian /usr/bin/drone-server