#!/usr/bin/with-contenv bash

if [[ -e /run/docker.sock ]]; then
  DGID="$(stat /run/docker.sock | awk '/Gid/ {print $(NF-1)+0}')"
  if [[ ! -z "${DGID}" ]]; then
    groupmod -o -g "$DGID" docker
    usermod -a -G docker guardian
  fi
fi
