#!/usr/bin/with-contenv bash

if [[ ! -d /mnt/config/data/drone/db ]]; then
  s6-setuidgid guardian mkdir -p /mnt/config/data/drone/db
fi
if [[ ! -d /mnt/config/etc/drone ]]; then
  s6-setuidgid guardian mkdir -p /mnt/config/etc/drone
fi

if [[ ! -e /mnt/config/etc/drone/config ]]; then
  s6-setuidgid guardian touch /mnt/config/etc/drone/config

  if [[ -z "${DRONE_DATABASE_SECRET}" ]]; then
    echo "export DRONE_DATABASE_SECRET=$(openssl rand -hex 16)" >> /mnt/config/etc/drone/config
  fi
  if [[ -z "${DRONE_GITEA_SERVER}" && -z "${DRONE_GITHUB_SERVER}" && -z "${DRONE_GITLAB_SERVER}" ]]; then
    echo "#export DRONE_GITEA_SERVER=https://try.gitea.io" >> /mnt/config/etc/drone/config
    echo "#export DRONE_GITEA_CLIENT_ID=" >> /mnt/config/etc/drone/config
    echo "#export DRONE_GITEA_CLIENT_SECRET=" >> /mnt/config/etc/drone/config
    echo "#export DRONE_GITHUB_SERVER=https://github.com" >> /mnt/config/etc/drone/config
    echo "#export DRONE_GITHUB_CLIENT_ID=" >> /mnt/config/etc/drone/config
    echo "#export DRONE_GITHUB_CLIENT_SECRET=" >> /mnt/config/etc/drone/config
    echo "#export DRONE_GITLAB_SERVER=https://gitlab.com" >> /mnt/config/etc/drone/config
    echo "#export DRONE_GITLAB_CLIENT_ID=" >> /mnt/config/etc/drone/config
    echo "#export DRONE_GITLAB_CLIENT_SECRET=" >> /mnt/config/etc/drone/config
  fi
  if [[ -z "${DRONE_RPC_SECRET}" ]]; then
    echo "export DRONE_RPC_SECRET=$(openssl rand -hex 16)" >> /mnt/config/etc/drone/config
  fi
  if [[ -z "${DRONE_SERVER_PROTO}" ]]; then
    echo "export DRONE_SERVER_PROTO=http" >> /mnt/config/etc/drone/config
  fi
  if [[ -z "${DRONE_SERVER_HOST}" ]]; then
    echo "#export DRONE_SERVER_HOST=example.net" >> /mnt/config/etc/drone/config
  fi
  if [[ -z "${DRONE_USER_CREATE}" ]]; then
    echo "#export DRONE_USER_CREATE=username:octocat,admin:true" >> /mnt/config/etc/drone/config
  fi
fi