#!/command/with-contenv /bin/bash

# Create Log Directory

if [[ ! -d /mnt/config/log ]]; then
  /command/s6-setuidgid guardian /bin/mkdir -p /mnt/config/log
fi

# Start Runner

if [[ -f /mnt/config/etc/drone-config ]]; then
  . /mnt/config/etc/drone-config
fi
export DRONE_LOG_FILE=${DRONE_LOG_FILE:-"/mnt/config/log/drone-ssh-runner.log"}
export DRONE_RPC_PROTO=${DRONE_RPC_PROTO:-"${DRONE_SERVER_PROTO}"}
export DRONE_RPC_HOST=${DRONE_RPC_HOST:-"${DRONE_SERVER_HOST}"}
export DRONE_RUNNER_OS=${DRONE_RUNNER_OS:-"linux"}
export DRONE_RUNNER_ARCH=${DRONE_RUNNER_ARCH:-"amd64"}
export DRONE_RUNNER_NAME="$(hostname)-ssh"}

if [[ ! -z "${DRONE_RPC_SECRET}" && ! -z "${DRONE_RPC_HOST}" && -z "${DRONE_AGENT_DISABLED}" && -z "${DRONE_SSH_DISABLED}" ]]; then
  export HOME=/mnt/config/home
  exec /command/s6-setuidgid guardian /usr/bin/drone-runner-ssh
else
  sleep 300
  exit 0
fi
